# Generated by Django 3.2.5 on 2021-07-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20210725_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(default='Dublin', max_length=100),
            preserve_default=False,
        ),
    ]
