# Generated by Django 3.2.5 on 2021-07-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_order_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='eircode',
            field=models.CharField(default='D06G6T5', max_length=10),
            preserve_default=False,
        ),
    ]
