# Generated by Django 3.2.5 on 2021-07-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20210725_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(default='Dublin', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='eircode',
            field=models.CharField(default='d06k5k5', max_length=10),
            preserve_default=False,
        ),
    ]
