# Generated by Django 3.2.5 on 2021-07-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_auto_20210725_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='435345345', max_length=20),
            preserve_default=False,
        ),
    ]
