# Generated by Django 3.2.5 on 2021-07-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_alter_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='none', max_length=254),
        ),
    ]
